### PR TITLE
Hackney Update

### PR DESCRIPTION
**Pull request by evadne**
Revised URL Source

- Removed iBrowse
- Added Hackney, HTTPoison
- Added further runtime configuration of HTTPoison and Hackney via deep merge of inlined override or system-level configuration

This will be done as a “Minor” release after the previous stop-gap fix is deployed and distributed as a “Patch” release.

@holsee @tmjoen FYI.

### CODE REVIEW

**Comment by evadne** [comment]
Due to use of override, previous idea of stopgap iBrowse release is not viable anymore

We will test Hackney based solution

**Comment by idabmat** [comment]
Thank you for this. We took it for a spin and it is working most of the time. But we do get some random CI failures with the changes in this PR. I was able to experience it running one of our apps locally as well. The error is terse and I don't have a stacktrace. I'm pasting it here in case it might mean something to you
```
[error] Unexpected message: {:tcp, #Port<0.175>, <<133, 191, 25, 244, 182, 180, 228, 185, 177, 155, 221, 121, 242, 44, 217, 181, 181, 181, 250, 107, 189, 61, 221, 199, 46, 32, 157, 152, 152, 138, 202, 223, 205, 64, 251, 93, 35, 43, 129, 7, 7, 251, 222, 245, 182, 35, 247, ...>>}
```

In the meantime, I'll try to see if I can reproduce it consistently.

**Comment by ftes** [comment]
This might be related: https://github.com/benoitc/hackney/issues/224.

Especially see [this comment](https://github.com/benoitc/hackney/issues/224#issuecomment-1779648519) from Oct 25, 2023:

> This issue occurs for us quite often is test environments using the latest hackney. It will usually occur when:
> - We have an HTTP stream enumerable running using hackney
> - We have an HTTP stream collectable running using hackney
> 
> The combination of these two streams running will usually result in:
> ```[error] Unexpected message: {:tcp, #Port<0.53>, <<13, 101, 109, 97, 105, 108, 95, 97, 100, 100, 114, 101, 115, 115, 0, 21, 12, 37, 0, 24, 10, 99, 111, 110, 116, 97, 99, 116, 95, 105, 100, 0, 21, 12, 37, 0, 24, 12, 114, 101, 102, 101, 114, 101, 110, 99, 101, ...>>}```
> And an eventual timeout from one of the streams.

**Comment by ftes** [comment]
Here's a drop-in replacement for `Packmatic.Source.URL`, using `finch` instead of `hackney`.
This should help avoid the error. There might be other trade-offs I'm yet unaware of.
Will try to keep you posted as we evaluated this solution.

```ex
defmodule My.Source.Finch do
  @behaviour Packmatic.Source
  @otp_app :my_app
  @finch_name MyFinch

  defstruct url: nil, ref: nil

  @impl Packmatic.Source
  def validate(%URI{scheme: "http"}), do: :ok
  def validate(%URI{scheme: "https"}), do: :ok
  def validate(url) when is_binary(url), do: validate(URI.parse(url))
  def validate(_), do: {:error, :invalid}

  @impl Packmatic.Source
  def init(target) do
    url = to_string(target)
    req = Finch.build(:get, url)
    options = Application.get_env(@otp_app, __MODULE__, [])
    ref = Finch.async_request(req, @finch_name, options)

    {:ok, %__MODULE__{url: url, ref: ref}}
  end

  @impl Packmatic.Source
  def read(%__MODULE__{ref: ref}) do
    receive do
      {^ref, {:status, 200}} -> <<>>
      {^ref, {:status, status}} -> {:error, {:unsupported_status, status}}
      {^ref, {:headers, _}} -> <<>>
      {^ref, {:data, data}} -> data
      {^ref, {:error, reason}} -> {:error, reason}
      {^ref, :done} -> :eof
      _ -> <<>>
    end
  end
end
```

**Pull request merged**
